// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDDr0LxI88j138sxepC7gXpRTbzKvCc38',
    appId: '1:220079051176:web:764768abe40305f1170d9d',
    messagingSenderId: '220079051176',
    projectId: 'loginutp-b73ea',
    authDomain: 'loginutp-b73ea.firebaseapp.com',
    storageBucket: 'loginutp-b73ea.firebasestorage.app',
    measurementId: 'G-77CHL5P23L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiSGyFGL2dIrtodmTY6MZdDbANZI4K5pg',
    appId: '1:220079051176:android:6e0e3cd65250bd30170d9d',
    messagingSenderId: '220079051176',
    projectId: 'loginutp-b73ea',
    storageBucket: 'loginutp-b73ea.firebasestorage.app',
  );
}
